Fix up build and release GitHub Actions, add CHANGELOG.md

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -24,8 +24,10 @@ permissions:
 
 #
 # Release (on tag semantic versioning style v1.2.3):
-# - Download .so libraries from GitHub Packages.
-# - Rename each .sha.so library .<version>.so
+# - Download .a libraries from GitHub Packages.
+# - Rename each .sha.a library .<version>.a
+# - Extract the object files into ./build/libutf8lex, and build new .so files
+#   and executables
 # - Commit to the dist/ directory under the appropriate architecture (i386 etc).
 #
 on:
@@ -44,10 +46,11 @@ jobs:
     runs-on: ubuntu-latest
 
     env:
-      DIST_DIR: ./dist
+      DEBIAN_IMAGE_BASE: "utf8lex-debian"
       UTF8LEX_DOWNLOAD_VERSION: "${{github.sha}}"
       UTF8LEX_RELEASE_TAG: "${{github.ref_name}}"  # git tag v1.2.3
-      SHARED_LIBRARY_BASE: "libutf8lex.so"
+      LIBRARY_DYNAMIC_BASE: "libutf8lex.so"
+      LIBRARY_STATIC_BASE: "libutf8lex.a"
       PROGRAM_BASE: "utf8lex"
 
     steps:
@@ -91,11 +94,17 @@ jobs:
                                          | sed 's|^v||'`
             echo "UTF8LEX_RELEASE_VERSION=$UTF8LEX_RELEASE_VERSION" \
                 >> $GITHUB_ENV
-            SHARED_LIBRARY_DOWNLOAD="${{env.SHARED_LIBRARY_BASE}}.${{env.UTF8LEX_DOWNLOAD_VERSION}}"
-            echo "SHARED_LIBRARY_DOWNLOAD=$SHARED_LIBRARY_DOWNLOAD" \
+            DEBIAN_IMAGE_DOWNLOAD="${{env.DEBIAN_IMAGE_BASE}}.${{env.UTF8LEX_DOWNLOAD_VERSION}}"
+            echo "DEBIAN_IMAGE_DOWNLOAD=$DEBIAN_IMAGE_DOWNLOAD" \
                 >> $GITHUB_ENV
-            SHARED_LIBRARY_RELEASE="${{env.SHARED_LIBRARY_BASE}}.$UTF8LEX_RELEASE_VERSION"
-            echo "SHARED_LIBRARY_RELEASE=$SHARED_LIBRARY_RELEASE" \
+            DEBIAN_IMAGE_RELEASE="${{env.DEBIAN_IMAGE_BASE}}.$UTF8LEX_RELEASE_VERSION"
+            echo "DEBIAN_IMAGE_RELEASE=$LIBRARY_STATIC_RELEASE" \
+                >> $GITHUB_ENV
+            LIBRARY_STATIC_DOWNLOAD="${{env.LIBRARY_STATIC_BASE}}.${{env.UTF8LEX_DOWNLOAD_VERSION}}"
+            echo "LIBRARY_STATIC_DOWNLOAD=$LIBRARY_STATIC_DOWNLOAD" \
+                >> $GITHUB_ENV
+            LIBRARY_STATIC_RELEASE="${{env.LIBRARY_STATIC_BASE}}.$UTF8LEX_RELEASE_VERSION"
+            echo "LIBRARY_STATIC_RELEASE=$LIBRARY_STATIC_RELEASE" \
                 >> $GITHUB_ENV
             PROGRAM_DOWNLOAD="${{env.PROGRAM_BASE}}.${{env.UTF8LEX_DOWNLOAD_VERSION}}"
             echo "PROGRAM_DOWNLOAD=$PROGRAM_DOWNLOAD" \
@@ -104,10 +113,59 @@ jobs:
             echo "PROGRAM_RELEASE=$PROGRAM_RELEASE" \
                 >> $GITHUB_ENV
             echo "UTF8LEX_RELEASE_VERSION=$UTF8LEX_RELEASE_VERSION"
-            echo "SHARED_LIBRARY_DOWNLOAD=$SHARED_LIBRARY_DOWNLOAD"
-            echo "SHARED_LIBRARY_RELEASE=$SHARED_LIBRARY_RELEASE"
+            echo "LIBRARY_STATIC_DOWNLOAD=$LIBRARY_STATIC_DOWNLOAD"
+            echo "LIBRARY_STATIC_RELEASE=$LIBRARY_STATIC_RELEASE"
             echo "PROGRAM_DOWNLOAD=$PROGRAM_DOWNLOAD"
             echo "PROGRAM_RELEASE=$PROGRAM_RELEASE"
+
+      #
+      # Extract release notes from the CHANGELOG.md:
+      # https://github.com/release-flow/keep-a-changelog-action/blob/main/docs/query.md
+      #
+      # The CHANGELOG.md must already have been updated to contain
+      # the version number (e.g. if "git tag v1.2.3", then "1.2.3"
+      # must be included in CHANGELOG.md).
+      #
+      - name: release-notes
+        id: query-release-info
+        uses: release-flow/keep-a-changelog-action@v2
+        with:
+          command: query
+          version: ${{env.UTF8LEX_RELEASE_VERSION}}
+          changelog: ./CHANGELOG.md
+
+      - name: generate-release-notes
+        run: |
+          rm -rf /tmp/release_notes.md
+          echo "# ${{env.UTF8LEX_RELEASE_VERSION}}" \
+              >> /tmp/release_notes.md
+          echo "Date: {{ steps.query-release-info.outputs.release-date }}" \
+              >> /tmp/release_notes.md
+          echo "${{ steps.query-release-info.outputs.release-notes }}" \
+              >> /tmp/release_notes.md
+          cat /tmp/release_notes.md
+
+      - name: release-type
+        run: |
+          echo "Is ${{env.UTF8LEX_RELEASE_VERSION}} a pre-release?"
+          MAYBE_PRERELEASE=`echo "${{env.UTF8LEX_RELEASE_VERSION}}" \
+                                | sed 's|^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$||'`
+          if test -z "$MAYBE_PRERELEASE"
+          then
+              echo "Full release."
+              IS_PRERELEASE=false
+              IS_LATEST=true
+          else
+              echo "Pre-release."
+              IS_PRERELEASE=true
+              IS_LATEST=false
+          fi
+          echo IS_PRERELEASE=$IS_PRERELEASE \
+              >> $GITHUB_ENV
+          echo "IS_PRERELEASE=$IS_PRERELEASE"
+          echo IS_LATEST=$IS_LATEST \
+              >> $GITHUB_ENV
+          echo "IS_LATEST=$IS_LATEST"
 
       - id: download-all_artifacts
         name: Download utf8lex libraries and programs for all architectures
@@ -138,12 +196,19 @@ jobs:
           use_unzip: false
           merge_multiple: false
 
-      - id: copy-utf8lex
-        name: Copy utf8lex binaries to dist directory
+      # Add support for more platforms with QEMU
+      # https://github.com/docker/setup-qemu-action
+      - id: qemu-setup
+        name: qemu for multi-platform docker support
+        if: steps.container-image-cache-restore.outputs.cache-hit != 'true'
+        uses: docker/setup-qemu-action@v3
+
+      - id: re-version
+        name: Extract from .a static library, re-version .so dynamic library
         run: |
           echo "utf8lex binaries downloaded from GitHub Packages:"
           find /tmp/utf8lex/ -type f
-          echo "Copying utf8lex libraries, programs into dist/..."
+          sudo systemctl start docker
           for MATRIX_PLATFORM in \
               linux/386 \
               linux/amd64 \
@@ -156,57 +221,107 @@ jobs:
               echo "MATRIX_PLATFORM=$MATRIX_PLATFORM"
               DEBIAN_ARCHITECTURE=`./get_debian_architecture.sh "$MATRIX_PLATFORM"`
               echo "DEBIAN_ARCHITECTURE=$DEBIAN_ARCHITECTURE"
-              rm -rf ${{env.DIST_DIR}}/$DEBIAN_ARCHITECTURE
-              mkdir -p ${{env.DIST_DIR}}/$DEBIAN_ARCHITECTURE
-              cp /tmp/utf8lex/${{env.SHARED_LIBRARY_DOWNLOAD}}.$DEBIAN_ARCHITECTURE/${{env.SHARED_LIBRARY_DOWNLOAD}}.$DEBIAN_ARCHITECTURE \
-                  ${{env.DIST_DIR}}/$DEBIAN_ARCHITECTURE/${{env.SHARED_LIBRARY_RELEASE}}
-              cp /tmp/utf8lex/${{env.PROGRAM_DOWNLOAD}}.$DEBIAN_ARCHITECTURE/${{env.PROGRAM_DOWNLOAD}}.$DEBIAN_ARCHITECTURE \
-                  ${{env.DIST_DIR}}/$DEBIAN_ARCHITECTURE/${{env.PROGRAM_RELEASE}}
-              chmod a+x ${{env.DIST_DIR}}/$DEBIAN_ARCHITECTURE/${{env.PROGRAM_RELEASE}}
+              rm -rf ${{env.BUILD_DIR}}
+              mkdir -p ${{env.BUILD_DIR}}
+              chmod -R a+w ${{env.BUILD_DIR}}
+
+              echo "Loading Docker buider image"
+              cp /tmp/utf8lex/${{env.DEBIAN_IMAGE_BASE}}.$DEBIAN_ARCHITECTURE.*.tar \
+                  ${{env.BUILD_DIR}}/${{env.DEBIAN_IMAGE_BASE}}.$DEBIAN_ARCHITECTURE.${{env.UTF8LEX_RELEASE_VERSION}}.tar
+              DEBIAN_IMAGE=`docker image load \
+                                --input ${{env.BUILD_DIR}}/${{env.DEBIAN_IMAGE_BASE}}.${{env.DEBIAN_ARCHITECTURE}}.${{env.UTF8LEX_RELEASE_VERSION}}.tar \
+                                | grep 'Loaded image:' \
+                                | tail -1 \
+                                | awk '{ print $NF; }'`
+              if test -z "$DEBIAN_IMAGE"
+              then
+                  echo "ERROR Failed to load Debian builder image ${{env.BUILD_DIR}}/${{env.DEBIAN_IMAGE_BASE}}.${{env.DEBIAN_ARCHITECTURE}}.${{env.UTF8LEX_RELEASE_VERSION}}.tar: could not determine image tag" >&2
+                  exit 1
+              fi
+              rm ${{env.BUILD_DIR}}/${{env.DEBIAN_IMAGE_BASE}}.${{env.DEBIAN_ARCHITECTURE}}.${{env.UTF8LEX_RELEASE_VERSION}}.tar
+
+              echo "Copying .a into place"
+              cp /tmp/utf8lex/${{env.LIBRARY_STATIC_DOWNLOAD}}
+                  ${{env.BUILD_DIR}}/${{env.LIBRARY_STATIC_RELEASE}}
+
+              echo "Running make re-version UTF8LEX_VERSION=${{env.UTF8LEX_RELEASE_VERSION}}"
+              #
+              # docker run documentation:
+              #     https://docs.docker.com/reference/cli/docker/container/run/
+              #
+              docker run \
+                      --rm \
+                      --platform "${{matrix.platform}}" \
+                      --volume `pwd`:/utf8lex:rw \
+                      "$DEBIAN_IMAGE" \
+                      make re-version \
+                          BUILD_DIR=../${{env.BUILD_DIR}} \
+                          UTF8LEX_VERSION=${{env.UTF8LEX_RELEASE_VERSION}}
           done
 
+      - id: prepare-utf8lex-for-upload
+        name: Prepare utf8lex (libraries, executables, ...) for release upload
+        run: |
+          echo "Preparing utf8lex assets for release"
+          rm -rf /tmp/utf8lex/
+          mkdir -p /tmp/utf8lex/
+          echo "Copying libraries and programs for release"
+          for MATRIX_PLATFORM in \
+              linux/386 \
+              linux/amd64 \
+              linux/arm/v7 \
+              linux/arm64 \
+              linux/mips64le \
+              linux/ppc64le \
+              linux/s390x
+          do
+              echo "MATRIX_PLATFORM=$MATRIX_PLATFORM"
+              DEBIAN_ARCHITECTURE=`./get_debian_architecture.sh "$MATRIX_PLATFORM"`
+              echo "DEBIAN_ARCHITECTURE=$DEBIAN_ARCHITECTURE"
+              cp ${{env.BUILD_DIR}}/${{env.LIBRARY_DYNAMIC}} \
+                  /tmp/utf8lex/${{env.LIBRARY_DYNAMIC}}.${{env.DEBIAN_ARCHITECTURE}}
+              cp ${{env.BUILD_DIR}}/${{env.LIBRARY_STATIC}} \
+                  /tmp/utf8lex/${{env.LIBRARY_STATIC}}.${{env.DEBIAN_ARCHITECTURE}}
+              cp ${{env.BUILD_DIR}}/${{env.PROGRAM}} \
+                  /tmp/utf8lex/${{env.PROGRAM}}.${{env.DEBIAN_ARCHITECTURE}}
+          done
+          echo "Removing all gitignore directories"
+          for DIR in `cat .gitignore`
+          do
+              rm -rf "$DIR"
+          done
+          echo "Bundling up source for release"
+          cd ..
+          tar czf /tmp/utf8lex/utf8lex-${{env.UTF8LEX_RELEASE_VERSION}}.tar.gz \
+              utf8lex
+          zip /tmp/utf8lex/utf8lex-${{env.UTF8LEX_RELEASE_VERSION}}.zip \
+              utf8lex
+          cd utf8lex
+
       #
-      # https://github.com/marketplace/actions/add-commit
+      # https://github.com/softprops/action-gh-release
       #
-      - id: commit-release-to-git
-        name: Commit release files to git
-        uses: EndBug/add-and-commit@v9
+      - name: Release
+        uses: softprops/action-gh-release@v2
         with:
-          # Use --no-ignore-removal to remove deleted dist files.
-          add: ${{env.DIST_DIR}} --no-ignore-removal
-
-          # author_name: default (author of the git tag).
-          # author_email: default (author of the git tag).
-          # commit: ''
-          # committer_name: (author_name)
-          # committer_email: (author_email)
-          # cwd: default (.)
-
-          # Determines the way the action fills missing author name and email.
-          # Three options are available:
-          # - github_actor -> UserName <UserName@users.noreply.github.com>
-          # - user_info -> Your Display Name <your-actual@email.com>
-          # - github_actions -> github-actions <email associated with the github logo>
-          # Default: github_actor
-          default_author: github_actor
-          fetch: --no-tags --force origin main
-          message: "Release ${{env.UTF8LEX_RELEASE_TAG}}"
-
-          # new_branch: (no new branch)
-
-          # The way the action should handle pathspec errors
-          # from the add and remove commands. Three options are available:
-          # - ignore -> errors will be logged but the step won't fail
-          # - exitImmediately -> the action will stop right away,
-          #                      and the step will fail
-          # - exitAtEnd -> the action will go on, every pathspec error
-          #                will be logged at the end, the step will fail.
-          # Default: ignore
-          pathspec_error_handling: exitImmediately
-
-          pull: '--rebase --autostash'
-          push: origin HEAD:main
-          # remove: default (do not remove anything)
-          tag: ${{env.UTF8LEX_RELEASE_VERSION}}
-          tag_push: '--force'
+          body_path: /tmp/release_notes.md
+          draft: false
+          prerelease: ${{env.IS_PRERELEASE}}
+          preserve_order: true
+          files: |
+            README.md
+            LICENSE
+            CHANGELOG.md
+            /tmp/utf8lex/*
+          overwrite_files: true
+          name: ${{env.UTF8LEX_RELEASE_TAG}}
+          tag_name: ${{env.UTF8LEX_RELEASE_TAG}}
+          fail_on_unmatched_files: true
+          # repository	String	Name of a target repository in <owner>/<repo> format. Defaults to GITHUB_REPOSITORY env variable
+          target_commitish: ${{env.UTF8LEX_DOWNLOAD_VERSION}}
+          # token	String	Secret GitHub Personal Access Token. Defaults to ${{ github.token }}
+          # discussion_category_name	String	If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "Managing categories for discussions in your repository."
+          generate_release_notes: false
+          append_body: false
+          make_latest: ${{env.IS_LATEST}}
   # --------------------------------------------------------------------
diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -57,6 +57,13 @@ LD_PROGRAM_FLAGS = -Wl,--no-as-needed -lpcre2-8 -lutf8proc
 #
 # Anyhoo we'll use the "-l:libxyz.a" syntax for now.
 #
+# (We decided not to statically link utf8lex executable after all,
+# since the standard c library causes problems for valgrind.  Abort mission!
+# Now we dynamically link all libraries for the ut8lex executable,
+# but statically link the .o files for utf8lex itself, since
+# no distribution in the universe today has libutf8lex.so.
+# Happy compromise.)
+#
 LDSTATIC_EXTRACT = ar
 LDSTATIC_EXTRACT_FLAGS = -x -o
 LDSTATIC_LIBRARY = ar
@@ -210,6 +217,42 @@ $(PROGRAM): $(OBJECT_FILES) $(BUILD_DIR)/libutf8lex/utf8lex.o
 
 .PHONY: build
 build: $(LIBRARY_DYNAMIC) $(LIBRARY_STATIC) $(PROGRAM)
+
+#
+# E.g.: make re-version UTF8LEX_VERSION=1.2.3
+#
+# To make the release process (Docker within GitHub Actions)
+# less excruciatingly painful (but still excruciatingly painful),
+# we re-use the .a file generated during the last commit to the main
+# branch, but then explode it, and re-build the .o files into
+# a newly versioned .so dynamic library.
+#
+# GitHub Actions has to copy the previously-built static library
+# (build/libutf8lex.a.(githuba_hash).(debian_architecture)),
+# and rename it to the new version (build/libutf8lex.a.1.2.3
+# with no architecture in the name), to produce the .so being built
+# (build/libutf8lex.so.1.2.3).
+#
+.PHONY: re-version-explode-archive
+re-version-explode-archive:
+	@echo "Exploding archive to re-version $(UTF8LEX_VERSION)..."
+	@if test ! -f "$(LIBRARY_STATIC)"; \
+	then \
+	    echo "ERROR $(LIBRARY_STATIC) does not exist" >&2; \
+	    echo "ERROR Copy previously built .a to $(LIBRARY_STATIC) and try again" >&2; \
+	    exit 1; \
+	fi
+	rm -rf $(BUILD_DIR)/libutf8lex
+	mkdir -p $(BUILD_DIR)/libutf8lex
+	cd $(BUILD_DIR)/libutf8lex \
+	    && $(LDSTATIC_EXTRACT) $(LDSTATIC_EXTRACT_FLAGS) \
+	        ../libutf8lex.a.$(UTF8LEX_VERSION)
+	cd "$(ORIGINAL_DIR)"
+	touch $(BUILD_DIR)/libutf8lex/*.o
+	@echo "SUCCESS Exploding archive to re-version $(UTF8LEX_VERSION)."
+
+.PHONY: re-version
+re-version: re-version-explode-archive $(LIBRARY_DYNAMIC) $(PROGRAM)
 
 .PHONY: clean
 clean:
